/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Menu;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.ArrayList;

/**
 *
 * @author franp
 */
public class GUI_Menu extends javax.swing.JFrame {

    GUI_Nivel guiNivel;
    Controlador_Menu controladorMenu;

    /**
     * Creates new form GUI_Menu
     */
    public GUI_Menu() {
        initComponents();
        this.guiNivel = new GUI_Nivel();
        this.controladorMenu = new Controlador_Menu(this, this.guiNivel);
        this.setSize(946, 563);
        this.setTitle("Carritos Chocones");
        this.requestFocus(true);
        this.addKeyListener(this.controladorMenu);
        this.setActionControlador(controladorMenu);
        this.setKeyControlador(controladorMenu);
    }

    public void setActionControlador(ActionListener controladorMenu) {
        jb_Nivel1.addActionListener(controladorMenu);
        jb_Nivel2.addActionListener(controladorMenu);
        jb_Nivel3.addActionListener(controladorMenu);
    }

    public void setKeyControlador(KeyListener controladorMenu) {
        jb_Nivel1.addKeyListener(controladorMenu);
        jb_Nivel2.addKeyListener(controladorMenu);
        jb_Nivel3.addKeyListener(controladorMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Dificultad = new javax.swing.JLabel();
        jb_Nivel1 = new javax.swing.JButton();
        jb_Nivel2 = new javax.swing.JButton();
        jb_Nivel3 = new javax.swing.JButton();
        jl_FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jl_Dificultad.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_Dificultad.setText("Escoja la dificultad:");
        getContentPane().add(jl_Dificultad);
        jl_Dificultad.setBounds(610, 480, 250, 17);

        jb_Nivel1.setText("Nivel 1");
        getContentPane().add(jb_Nivel1);
        jb_Nivel1.setBounds(40, 50, 65, 23);

        jb_Nivel2.setText("Nivel 2");
        getContentPane().add(jb_Nivel2);
        jb_Nivel2.setBounds(40, 100, 65, 23);

        jb_Nivel3.setText("Nivel 3");
        getContentPane().add(jb_Nivel3);
        jb_Nivel3.setBounds(40, 150, 65, 23);

        jl_FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu_Mario.jpg"))); // NOI18N
        getContentPane().add(jl_FondoMenu);
        jl_FondoMenu.setBounds(0, 0, 945, 532);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Nivel1;
    private javax.swing.JButton jb_Nivel2;
    private javax.swing.JButton jb_Nivel3;
    private javax.swing.JLabel jl_Dificultad;
    private javax.swing.JLabel jl_FondoMenu;
    // End of variables declaration//GEN-END:variables
}
