/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Nivel;
import Controlador.Controlador_Personaje;
import Modelo.Hilo_Fondo;
import Modelo.Hilo_Personaje;
import javax.swing.JLabel;

/**
 *
 * @author franp
 */
public class GUI_Nivel extends javax.swing.JFrame {

    Hilo_Fondo hiloFondo;
    Hilo_Personaje personaje;
    Controlador_Personaje controladorPersonaje;
    Controlador_Nivel controladorNivel;

    /**
     * Creates new form GUI_Nivel
     */
    public GUI_Nivel() {
        initComponents();
        this.hiloFondo = new Hilo_Fondo(this);
        this.personaje = new Hilo_Personaje(this);
//        hiloFondo.start();// esto ejecuta el método run de hiloFondo
        this.setSize(861, 805);
        this.setTitle("Carritos Chocones");
        this.controladorPersonaje = new Controlador_Personaje(this, this.personaje, this.hiloFondo);
        this.addKeyListener(controladorPersonaje);
        this.controladorNivel = new Controlador_Nivel(this, this.hiloFondo);
        this.addComponentListener(controladorNivel);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
    }

    public JLabel getFondo() {
        return this.jl_Fondo;
    }

    public JLabel getPersonaje() {
        return this.jl_Personaje;
    }

    /* 
    Carril 1: 250
    Carril 2: 420
    Carril 3: 570
     */
    public void setNuevoEnemigo(int identificador, int ubicacionX, int ubicacionY) {
        int ubicacionRandomX = 0;
        int random = 1 + (int) (Math.random() * 3);
        switch (random) {
            case 1:
                ubicacionRandomX = 250;
                break;
            case 2:
                ubicacionRandomX = 420;
                break;
            case 3:
                ubicacionRandomX = 570;
                break;
            default:;
        }
        switch (identificador) {
            case 0:
                JLabel jl_Enemigo = new JLabel();
                jl_Enemigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carro_rojo.png")));
                getContentPane().add(jl_Enemigo);
                jl_Enemigo.setBounds(ubicacionRandomX, -100, 86, 112); //setBounds(x, y, width, height)
                break;
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;

            default:;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Personaje = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jl_Personaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carro_azul.png"))); // NOI18N
        getContentPane().add(jl_Personaje);
        jl_Personaje.setBounds(390, 580, 90, 120);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_juego.png"))); // NOI18N
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, -1160, 860, 1910);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Personaje;
    // End of variables declaration//GEN-END:variables
}
