/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Menu;

/**
 *
 * @author franp
 */
public class GUI_Menu extends javax.swing.JFrame {

    GUI_Nivel guiNivel;
    Controlador_Menu controladorMenu;

    /**
     * Creates new form GUI_Menu
     */
    public GUI_Menu() {
        initComponents();
        this.guiNivel = new GUI_Nivel();
        this.controladorMenu = new Controlador_Menu(guiNivel, this);
        this.addKeyListener(controladorMenu);
        this.setSize(946, 563);
        this.setTitle("Carritos Chocones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Dificultad = new javax.swing.JLabel();
        jcb_Dificultad = new javax.swing.JComboBox<>();
        jl_FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jl_Dificultad.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_Dificultad.setText("Escoja la dificultad:");
        getContentPane().add(jl_Dificultad);
        jl_Dificultad.setBounds(610, 480, 250, 17);

        jcb_Dificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcb_Dificultad);
        jcb_Dificultad.setBounds(860, 480, 56, 20);

        jl_FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu_Mario.jpg"))); // NOI18N
        getContentPane().add(jl_FondoMenu);
        jl_FondoMenu.setBounds(0, 0, 945, 532);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcb_Dificultad;
    private javax.swing.JLabel jl_Dificultad;
    private javax.swing.JLabel jl_FondoMenu;
    // End of variables declaration//GEN-END:variables
}
